import { Language } from '../types';

export const translations = {
  EN: {
    welcome: "Welcome",
    dashboard: "Dashboard",
    medicalRecords: "Medical Records",
    billing: "Billing",
    bookAppt: "Book Appointment",
    doctor: "Doctor",
    patient: "Patient",
    admin: "Admin",
    nic: "NIC Number",
    district: "District",
    phone: "Phone Number",
    consultation: "Consultation",
    total: "Total",
    payNow: "Pay Now",
    queueToken: "Queue Token",
    nowServing: "Now Serving",
    upNext: "Up Next",
    room: "Room",
    login: "Login to System",
    reason: "Reason",
    date: "Date",
    time: "Time",
    selectDoctor: "Select Doctor",
    symptoms: "Symptoms",
    prescription: "Prescription",
    aiAssistant: "AI Assistant",
    slmc: "SLMC No",
    loading: "Loading..."
  },
  SI: {
    welcome: "ආයුබෝවන්",
    dashboard: "පුවරුව",
    medicalRecords: "වෛද්‍ය වාර්තා",
    billing: "ගෙවීම්",
    bookAppt: "වේලාවක් වෙන්කරවා ගන්න",
    doctor: "වෛද්‍ය",
    patient: "රෝගියා",
    admin: "පරිපාලක",
    nic: "ජා.හැ.අංකය",
    district: "දිස්ත්‍රික්කය",
    phone: "දුරකථන අංකය",
    consultation: "වෛද්‍ය ගාස්තු",
    total: "එකතුව",
    payNow: "දැන් ගෙවන්න",
    queueToken: "පෝලිම් අංකය",
    nowServing: "දැන් සේවය සපයන අංකය",
    upNext: "ඊළඟ අංකය",
    room: "කාමර අංකය",
    login: "පද්ධතියට ඇතුල් වන්න",
    reason: "හේතුව",
    date: "දිනය",
    time: "වේලාව",
    selectDoctor: "වෛද්‍යවරයා තෝරන්න",
    symptoms: "රෝග ලක්ෂණ",
    prescription: "බෙහෙත් වට්ටෝරුව",
    aiAssistant: "AI සහායක",
    slmc: "SLMC අංකය",
    loading: "රැඳී සිටින්න..."
  },
  TA: {
    welcome: "வணக்கம்",
    dashboard: "முகப்பு",
    medicalRecords: "மருத்துவ பதிவுகள்",
    billing: "பட்டியலிடல்",
    bookAppt: "நியமனம் பதிவு",
    doctor: "மருத்துவர்",
    patient: "நோயாளி",
    admin: "நிர்வாகி",
    nic: "தேசிய அடையாள அட்டை",
    district: "மாவட்டம்",
    phone: "தொலைபேசி எண்",
    consultation: "ஆலோசனை",
    total: "மொத்தம்",
    payNow: "இப்போது பணம் செலுத்துங்கள்",
    queueToken: "வரிசை டோக்கன்",
    nowServing: "இப்போது அழைப்பது",
    upNext: "அடுத்து",
    room: "அறை",
    login: "உள்நுையவும்",
    reason: "காரணம்",
    date: "தேதி",
    time: "நேரம்",
    selectDoctor: "மருத்துவரைத் தேர்ந்தெடுக்கவும்",
    symptoms: "அறிகுறிகள்",
    prescription: "மருந்து சீட்டு",
    aiAssistant: "AI உதவியாளர்",
    slmc: "SLMC எண்",
    loading: "ஏற்றுகிறது..."
  }
};

export const getT = (lang: Language, key: keyof typeof translations['EN']) => {
  return translations[lang][key] || translations['EN'][key];
};